-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "MovementClass" ADD VALUE 'CHEST_HORIZONTAL_PRESS';
ALTER TYPE "MovementClass" ADD VALUE 'CHEST_INCLINE_PRESS';
ALTER TYPE "MovementClass" ADD VALUE 'CHEST_ADDUCTION_FLY';
ALTER TYPE "MovementClass" ADD VALUE 'CHEST_STRETCH_BIASED';
ALTER TYPE "MovementClass" ADD VALUE 'SHOULDER_VERTICAL_PRESS';
ALTER TYPE "MovementClass" ADD VALUE 'SHOULDER_LATERAL_ABDUCTION';
ALTER TYPE "MovementClass" ADD VALUE 'SHOULDER_REAR_DELT';
ALTER TYPE "MovementClass" ADD VALUE 'SHOULDER_LENGTHENED';
ALTER TYPE "MovementClass" ADD VALUE 'BICEP_SUPINATED_CURL';
ALTER TYPE "MovementClass" ADD VALUE 'BICEP_LENGTHENED';
ALTER TYPE "MovementClass" ADD VALUE 'BICEP_SHORTENED';
ALTER TYPE "MovementClass" ADD VALUE 'BICEP_NEUTRAL_BRACHIALIS';
ALTER TYPE "MovementClass" ADD VALUE 'TRICEP_PRESS_COMPOUND';
ALTER TYPE "MovementClass" ADD VALUE 'TRICEP_PUSHDOWN';
ALTER TYPE "MovementClass" ADD VALUE 'TRICEP_OVERHEAD_EXTENSION';
ALTER TYPE "MovementClass" ADD VALUE 'TRICEP_LENGTHENED';
ALTER TYPE "MovementClass" ADD VALUE 'QUAD_BILATERAL_SQUAT';
ALTER TYPE "MovementClass" ADD VALUE 'QUAD_MACHINE_PRESS';
ALTER TYPE "MovementClass" ADD VALUE 'QUAD_UNILATERAL';
ALTER TYPE "MovementClass" ADD VALUE 'QUAD_KNEE_EXTENSION';
ALTER TYPE "MovementClass" ADD VALUE 'HAMSTRING_HIP_HINGE';
ALTER TYPE "MovementClass" ADD VALUE 'HAMSTRING_KNEE_FLEXION';
ALTER TYPE "MovementClass" ADD VALUE 'HAMSTRING_UNILATERAL';
ALTER TYPE "MovementClass" ADD VALUE 'HAMSTRING_LENGTHENED';
