-- CreateEnum
CREATE TYPE "ExerciseCategory" AS ENUM ('PRIMARY_COMPOUND', 'COMPOUND_ACCESSORY', 'ISOLATION_PRIMARY', 'ISOLATION_AUXILIARY');

-- AlterTable
ALTER TABLE "Exercise" ADD COLUMN     "category" "ExerciseCategory" NOT NULL DEFAULT 'PRIMARY_COMPOUND';
