export const AUTH_EVENTS = {
  REGISTRATION: 'REGISTRATION',
  VERIFICATION_SENT: 'VERIFICATION_SENT',
  VERIFICATION_COMPLETED: 'VERIFICATION_COMPLETED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',
  REFRESH_TOKEN_REUSE: 'REFRESH_TOKEN_REUSE',
  LOGOUT: 'LOGOUT',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
} as const;

export const AUTH_FAILURE_REASONS = {
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  BRUTE_FORCE: 'BRUTE_FORCE',
} as const;

export type AuthEvent = (typeof AUTH_EVENTS)[keyof typeof AUTH_EVENTS];
export type AuthFailureReason =
  (typeof AUTH_FAILURE_REASONS)[keyof typeof AUTH_FAILURE_REASONS];
